name: Markdown-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Lint documentation
      run: |
        npm install
        node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5
